# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-16 16:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_expire', models.DateTimeField(default=datetime.datetime(2019, 5, 17, 0, 0, 23, 151212))),
                ('v_price', models.FloatField(default=1)),
                ('v_status', models.IntegerField(default=0)),
                ('v_seats', models.CharField(max_length=256)),
                ('v_paidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cinema.PaiDang')),
            ],
        ),
        migrations.CreateModel(
            name='ViewerPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_user_id', models.IntegerField(default=0)),
                ('v_permission_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ViewerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_username', models.CharField(max_length=32, unique=True)),
                ('v_password', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='viewerorder',
            name='v_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Viewer.ViewerUser'),
        ),
    ]
