# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-21 04:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viewer', '0002_viewerorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewerorder',
            name='v_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 12, 47, 12, 811662)),
        ),
    ]
