# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-21 07:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viewer', '0003_auto_20190221_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewerorder',
            name='v_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 15, 8, 53, 992576)),
        ),
    ]
