# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-08 03:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viewer', '0005_auto_20190425_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewerorder',
            name='v_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 11, 41, 12, 527660)),
        ),
    ]
