# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-13 01:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viewer', '0006_auto_20190508_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewerorder',
            name='v_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 9, 28, 17, 383766)),
        ),
    ]
