# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-16 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=64)),
                ('c_address', models.CharField(max_length=128)),
                ('c_phone', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CinemaMovieOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_status', models.IntegerField(default=0)),
                ('c_price', models.FloatField(default=0)),
                ('is_delete', models.BooleanField(default=False)),
                ('c_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='CinemaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_username', models.CharField(max_length=32, unique=True)),
                ('c_password', models.CharField(max_length=256)),
                ('is_delete', models.BooleanField(default=False)),
                ('c_permission', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=32)),
                ('h_seats', models.CharField(max_length=256)),
                ('h_cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cinema.Cinema')),
            ],
        ),
        migrations.CreateModel(
            name='PaiDang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_time', models.DateTimeField(default='2018-12-13 00:00:00')),
                ('p_time_end', models.DateTimeField(default='2018-12-13 02:00:00')),
                ('p_price', models.FloatField(default=35)),
                ('p_cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cinema.Cinema')),
                ('p_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cinema.Hall')),
                ('p_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='cinemamovieorder',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cinema.CinemaUser'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cinema.CinemaUser'),
        ),
    ]
